version: "2"
run:
  go: "1.23"
linters:
  default: none
  enable:
    - contextcheck
    - copyloopvar
    - decorder
    - errorlint
    - exptostd
    - gochecknoinits
    - gocritic
    - gosec
    - govet
    - ineffassign
    - intrange
    - nakedret
    - nilerr
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
        - singleCaseSwitch
        - ifElseChain
      enabled-tags:
        - performance
        - style
        - experimental
    govet:
      disable:
        - composites
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
    rules:
      - linters:
          - dupl
          - gosec
          - revive
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
