// Code generated by mockery v2.47.0. DO NOT EDIT.

package passkey

import (
	webauthn "github.com/go-webauthn/webauthn/webauthn"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: data
func (_m *MockSessionStore) Create(data webauthn.SessionData) (string, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(webauthn.SessionData) (string, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(webauthn.SessionData) string); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(webauthn.SessionData) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - data webauthn.SessionData
func (_e *MockSessionStore_Expecter) Create(data interface{}) *MockSessionStore_Create_Call {
	return &MockSessionStore_Create_Call{Call: _e.mock.On("Create", data)}
}

func (_c *MockSessionStore_Create_Call) Run(run func(data webauthn.SessionData)) *MockSessionStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(webauthn.SessionData))
	})
	return _c
}

func (_c *MockSessionStore_Create_Call) Return(_a0 string, _a1 error) *MockSessionStore_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_Create_Call) RunAndReturn(run func(webauthn.SessionData) (string, error)) *MockSessionStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: token
func (_m *MockSessionStore) Delete(token string) {
	_m.Called(token)
}

// MockSessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - token string
func (_e *MockSessionStore_Expecter) Delete(token interface{}) *MockSessionStore_Delete_Call {
	return &MockSessionStore_Delete_Call{Call: _e.mock.On("Delete", token)}
}

func (_c *MockSessionStore_Delete_Call) Run(run func(token string)) *MockSessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionStore_Delete_Call) Return() *MockSessionStore_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionStore_Delete_Call) RunAndReturn(run func(string)) *MockSessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: token
func (_m *MockSessionStore) Get(token string) (*webauthn.SessionData, bool) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *webauthn.SessionData
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*webauthn.SessionData, bool)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *webauthn.SessionData); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webauthn.SessionData)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - token string
func (_e *MockSessionStore_Expecter) Get(token interface{}) *MockSessionStore_Get_Call {
	return &MockSessionStore_Get_Call{Call: _e.mock.On("Get", token)}
}

func (_c *MockSessionStore_Get_Call) Run(run func(token string)) *MockSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionStore_Get_Call) Return(_a0 *webauthn.SessionData, _a1 bool) *MockSessionStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_Get_Call) RunAndReturn(run func(string) (*webauthn.SessionData, bool)) *MockSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
