// Code generated by mockery v2.47.0. DO NOT EDIT.

package passkey

import (
	webauthn "github.com/go-webauthn/webauthn/webauthn"
	mock "github.com/stretchr/testify/mock"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// DeleteSession provides a mock function with given fields: token
func (_m *MockSessionStore) DeleteSession(token string) {
	_m.Called(token)
}

// MockSessionStore_DeleteSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSession'
type MockSessionStore_DeleteSession_Call struct {
	*mock.Call
}

// DeleteSession is a helper method to define mock.On call
//   - token string
func (_e *MockSessionStore_Expecter) DeleteSession(token interface{}) *MockSessionStore_DeleteSession_Call {
	return &MockSessionStore_DeleteSession_Call{Call: _e.mock.On("DeleteSession", token)}
}

func (_c *MockSessionStore_DeleteSession_Call) Run(run func(token string)) *MockSessionStore_DeleteSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionStore_DeleteSession_Call) Return() *MockSessionStore_DeleteSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionStore_DeleteSession_Call) RunAndReturn(run func(string)) *MockSessionStore_DeleteSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: token
func (_m *MockSessionStore) GetSession(token string) (*webauthn.SessionData, bool) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *webauthn.SessionData
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*webauthn.SessionData, bool)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *webauthn.SessionData); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*webauthn.SessionData)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockSessionStore_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockSessionStore_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - token string
func (_e *MockSessionStore_Expecter) GetSession(token interface{}) *MockSessionStore_GetSession_Call {
	return &MockSessionStore_GetSession_Call{Call: _e.mock.On("GetSession", token)}
}

func (_c *MockSessionStore_GetSession_Call) Run(run func(token string)) *MockSessionStore_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSessionStore_GetSession_Call) Return(_a0 *webauthn.SessionData, _a1 bool) *MockSessionStore_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_GetSession_Call) RunAndReturn(run func(string) (*webauthn.SessionData, bool)) *MockSessionStore_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function with given fields: token, data
func (_m *MockSessionStore) SaveSession(token string, data *webauthn.SessionData) {
	_m.Called(token, data)
}

// MockSessionStore_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type MockSessionStore_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - token string
//   - data *webauthn.SessionData
func (_e *MockSessionStore_Expecter) SaveSession(token interface{}, data interface{}) *MockSessionStore_SaveSession_Call {
	return &MockSessionStore_SaveSession_Call{Call: _e.mock.On("SaveSession", token, data)}
}

func (_c *MockSessionStore_SaveSession_Call) Run(run func(token string, data *webauthn.SessionData)) *MockSessionStore_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*webauthn.SessionData))
	})
	return _c
}

func (_c *MockSessionStore_SaveSession_Call) Return() *MockSessionStore_SaveSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionStore_SaveSession_Call) RunAndReturn(run func(string, *webauthn.SessionData)) *MockSessionStore_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
